### ISSUE TITLE
pdf load 2 times

### ISSUE THREAD

**Issue by mehranml** [DanielArnould/react-pdf-highlighter-extended#2]
after loading pdf we have 2 loaded pdf for example for 22 page pdf we have 44 page

**Comment by DanielArnould** [comment]
Could you elaborate more on this or provide some steps to reproduce this issue? Do you mean the page count for the pdf is doubled? Does the viewer display 2 stacked documents (i.e., after page 22, does it show page 1 again)? Does the document load just trigger twice?

**Comment by HenrikMader** [comment]
Also the same here. The viewer displays 2 stacked documents.

**Comment by mehranml** [comment]
Yes it's 2 stack after page 22 page 1 shows again

**Comment by DanielArnould** [comment]
The default PDF.js viewer appears to not handle immediate subsequent document loads, keeping pages in the initial rendering queue. I suspect you are either running your application in strict mode or changing documents very frequently. I've just fixed this by debouncing the viewer initialisation, but I hope I'm missing a better fix.

This is potentially related to https://github.com/mozilla/pdf.js/issues/10018 .

The fix will be released in version 7.1.0
